spring:
  application:
    name: useruidemoapp
#  data:
#    mongodb:
#      authentication-database: admin
#      database: user_db
#      username: root
#      password:
#        - root
#      port: 27017
#      host: localhost
server:
  port: 8081
